kind: Secret
apiVersion: v1
metadata:
  name: {{.Values.hcloud_csi.controller.hcloudToken.existingSecret.name}}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  {{.Values.hcloud_csi.controller.hcloudToken.existingSecret.key}}: {{ .Values.hcloud_token | b64enc | quote }}
