{{- if .Values.prometheus.enabled -}}
# https://github.com/hetznercloud/csi-driver/blob/main/docs/monitoring.md#prometheus-operator-servicemonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hcloud-csi-controller
  namespace: '{{.Values.namespace}}'
  labels:
{{ include "kubee-manifest-labels" . | indent 4}}
spec:
  jobLabel: "{{ .Release.Name }}-controller"
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      # as seen on the installed node
      app: hcloud-csi-controller
  endpoints:
    - port: metrics
      scheme: http
      interval: {{ .Values.prometheus.scrape_interval }}
{{- end -}}