# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: 'auth'

# @schema
# title: Hostname
# description: The public hostname
# required: true
# minLength: 1
# @schema
# -- The public hostname
# (Required as you need a callback)
hostname: ''

# -- Additional [auth connectors](https://dexidp.io/docs/connectors)
connectors: []

# Clients
# https://dexidp.io/docs/guides/using-dex/#configuring-your-app
clients:
  kubernetes:
    # @schema
    # const: 'kubernetes'
    # @schema
    # @ignored The Kubernetes client id (ie token audience, fix value)
    client_id: 'kubernetes'
    # -- List of kubernetes trusted client id
    # (All clients that needs kubernetes access should be in that list.)
    trusted_peers: []
  # -- Oauth2_proxy client
  oauth2_proxy:
    # @schema
    # const: 'oauth2-proxy'
    # @schema
    # The oauth2-proxy client id.
    # If changed, all kubee charts that depends on it should be deployed again (traefik,...)
    client_id: 'oauth2-proxy'
    # @schema
    # title: 'The oauth2-proxy client id secret'
    # @schema
    # The oidc client secret (It is used to exchange the code between oauth2-proxy and dex).
    # Example: `openssl rand -base64 32`
    secret: ''
  # -- ArgoCd Web client
  argocd:
    # @schema
    # const: 'argocd'
    # @schema
    # The argocd web client id.
    # If changed, argocd needs to be redeployed
    client_id: 'argocd'
    # @schema
    # title: 'The argocd client id secret'
    # @schema
    # The argocd client secret (It is used to exchange the code between argocd and dex).
    # Example: `openssl rand -base64 32`
    secret: ''
  # -- ArgoCd terminal client (ie argocd login)
  argocd_cli:
    # @schema
    # const: 'argocd-cli'
    # @schema
    # The argocd terminal client id.
    # If changed, argocd needs to be redeployed
    client_id: 'argocd-cli'
  # -- Kubectl (ie kubectl oidc-login)
  # Added if the secret is not empty
  kubectl:
    # @schema
    # const: 'kubectl'
    # @schema
    # The kubectl client id
    client_id: 'kubectl' # If changed, all kubectl config should be modified
    # The oidc client secret (used to exchange the code between kubectl and dex)
    # Example: `openssl rand -base64 32`
    secret: ''
  # -- Postal client
  postal:
    # @schema
    # title: Postal Client Id
    # required: true
    # minLength: 1
    # @schema
    # The postal client id.
    # If changed, postal should be redeployed
    client_id: 'oauth2-proxy'
    # The oidc client secret (used to exchange the code between postal and dex)
    # Example: `openssl rand -base64 32`
    secret: ''


  # -- Other oidc clients definition to add your own clients. See the [doc](https://dexidp.io/docs/guides/using-dex/#configuring-your-app)
  others: []

# [Expiration settings](https://dexidp.io/docs/configuration/tokens/#expiration-and-rotation-settings)
# It's possible to specify units using only s, m and h suffixes.
# This configuration are used by Oauth proxy to set cookie expiration settings
expiration:
  # @schema
  # title: The access token lifetime
  # type: integer
  # required: true
  # @schema
  # -- The access token lifetime (in minutes)
  # 24h (1440m) is the [default](https://github.com/dexidp/dex/blob/65814bbd7746611a359408bb355fb4e12d6e2c14/config.yaml.dist#L89),
  # 10m is the [recommended doc setting](https://dexidp.io/docs/configuration/tokens/#expiration-and-rotation-settings),
  # 1m is the [recommended setting of Oauth proxy](https://oauth2-proxy.github.io/oauth2-proxy/configuration/session_storage).
  access_token_lifetime: 1440  # It must be an integer because the refresh process needs to be executed before and oauth-proxy needs a value so we need to apply some math.
  # @schema
  # title: The refresh token lifetime
  # type: integer
  # required: true
  # @schema
  # -- The refresh token lifetime (in minutes), it forces users to reauthenticate
  # 3960h (165 days) is the [dex default](https://github.com/dexidp/dex/blob/65814bbd7746611a359408bb355fb4e12d6e2c14/config.yaml.dist#L89),
  # 168h (7 days, 10080m) is the [default cookie_expire value](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview?_highlight=cookie_expire#cookie-options)
  refresh_token_lifetime: 10080



# @ignored
# Dex Chart Values
# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  configSecret:
    create: false # we do it
    name: "dex-kubee-config"
  image:
    # https://github.com/dexidp/dex/releases
    tag: 'v2.45.1'
  https:
    # False because it enable it with only one flag via command line and it conflicts with the configuration
    enabled: true
  # Deployment volumes
  # as seen here: https://github.com/dexidp/dex/blob/a6dfa5ca9f9e1c819a846bd667c3c357da5252ac/examples/k8s/dex.yaml#L34
  volumeMounts:
    - name: tls
      mountPath: /etc/dex/tls
  volumes:
    - name: tls
      secret:
        secretName: dex-kubee-tls
  serviceMonitor:
    enabled: true
  networkPolicy:
    enabled: true


# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false