#!/usr/bin/env bash

# This script download the kube-prometheus scripts
# for the prometheus chart

source bashlib-error.sh
error::set_strict_mode
error::set_trap
source bashlib-echo.sh

FILES=(
  "components/prometheus.libsonnet"
  "components/prometheus-operator.libsonnet"
  "components/kube-rbac-proxy.libsonnet"
  "components/alertmanager.libsonnet" # needed only for variable reference
  "versions.json"
  # Custom Mixin (ie general rules, particularly target down)
  # https://runbooks.prometheus-operator.dev/runbooks/general/
  "components/mixin/custom.libsonnet"
  "components/mixin/alerts/alerts.libsonnet"
  "components/mixin/alerts/general.libsonnet"
  "components/mixin/alerts/node.libsonnet"
  "components/mixin/rules/rules.libsonnet"
  "components/mixin/rules/general.libsonnet"
  "components/mixin/rules/node-rules.libsonnet"
)

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR"/prometheus-dependency-helper --jsonnet-dir="$SCRIPT_DIR/../jsonnet" "${FILES[@]}"