name: Deploy Astro to GitHub Pages

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to checkout (tag: vx.x.x or early-access, or branch name)'
        required: true
        type: string
        default: 'main'

  # Trigger on tag push
  push:
    # A tag is a commit name (as a branch)
    # We can't filter by default if a branch contains a tag
    tags:
      - 'v*'
      - 'early-access'


# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  WEBSITE_DIR: ./website

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ${{ env.WEBSITE_DIR }}/package-lock.json

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.WEBSITE_DIR }}

      - name: Build Astro site
        run: yarn build
        working-directory: ${{ env.WEBSITE_DIR }}
#        env:
#          SITE: ${{ steps.pages.outputs.origin }}
#          BASE_PATH: ${{ steps.pages.outputs.base_path }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WEBSITE_DIR }}/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
